// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.BIMIRecordValidator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("bimi_host")]
        public string BimiHost { get; set; }

        [JsonProperty("bimi_record")]
        public string BimiRecord { get; set; }

        [JsonProperty("bimi_records_count")]
        public long BimiRecordsCount { get; set; }

        [JsonProperty("has_bimi_record")]
        public bool HasBimiRecord { get; set; }

        [JsonProperty("host")]
        public string Host { get; set; }

        [JsonProperty("svg_logo")]
        public SvgLogo SvgLogo { get; set; }

        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("vmc_certificate")]
        public SvgLogo VmcCertificate { get; set; }
    }

    public partial class SvgLogo
    {
        [JsonProperty("file_size_bytes", NullValueHandling = NullValueHandling.Ignore)]
        public long? FileSizeBytes { get; set; }

        [JsonProperty("status_code")]
        public long StatusCode { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("valid")]
        public bool Valid { get; set; }
    }
}
